name: Build Docker Release Images

on:
  workflow_run:
    workflows: ["Build Docker Images"]
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"
    types: 
      - completed

env:
  AWS_REGISTRY: public.ecr.aws/genialis
  AWS_REGION: us-east-1

jobs:
  tagged:
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    strategy:
      fail-fast: false
      matrix:
        image: [ubuntu-20.04, communication]
        include:
          - image: ubuntu-20.04
            context: resolwe/toolkit/docker_images/base/
            file: resolwe/toolkit/docker_images/base/Dockerfile.ubuntu-20.04
            tags: genialis-test/base
          - image: communication
            context: resolwe/
            file: resolwe/flow/docker_images/Dockerfile.communication
            tags: genialis-test/com

    steps:
      - name: Get the docker image tag
        id: get_tag
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.file }}
          tags: ${{ env.AWS_REGISTRY }}/${{ matrix.tags }}:${{ steps.get_tag.outputs.VERSION }}
          push: true
